### ISSUE TITLE
Places 9 Torches and some don't place.

### ISSUE THREAD

**Issue by Wissi** [noriokun4649/TorchBowMod#1]
Great mod, we love it.

Found a couple bugs;
1- when you shoot, it shoots 9 torches (instead of just 1) and
2- tries to place them, but if there is grass, flowers, etc it will just drop the Torch w/o placing it. Even when it's just stone it will not place all 9 all the time.

Happens on both SSP and  on server (SMP). 
In Survival and in Creative.
I was under the impression that it would shoot/place only 1 at a time?
It does consume all 9 torches at once.

Using:
forge-28.0.83
[1.14.2-1.14.4]TorchBowMod_v1.4.jar

If it is a feature (that it throws and places 9 at once) then can there be a config option for only 1 instead of all 9? (Seems a waste of torches 9 in one place)
And maybe check why not all place everytime?

Awesome work, Thanks.

![Torches](https://user-images.githubusercontent.com/23312242/64393335-81f9cb00-d016-11e9-90c5-e640480c8f69.png)

![Torches2](https://user-images.githubusercontent.com/23312242/64393342-8aea9c80-d016-11e9-8697-4d3b48e5127a.png)

**Comment by noriokun4649** [comment]
1- when you shoot, it shoots 9 torches (instead of just 1) and

This is a function that allows multiple torches to be installed by using multi torches instead of torches.
When you look at the inventory, I think it's a multi torch. Do you use multi torches?

2- tries to place them, but if there is grass, flowers, etc it will just drop the Torch w/o placing it. Even when it's just stone it will not place all 9 all the time.

uh...
When multiple torches are placed, each torch vector is shifted and fired.
So if you put it near you, you might try to put it in the same block. If you try to place it in the same block, it will be dropped as an item.
If you shoot far, you can place several torches.
If I can correct it, I will adjust the detailed parameters so that it can be placed nearby.

A multi torch should be able to replace grass and flowers with a torch.

Finally, I found a bug in switching from a multi torch to a single torch that didn't work. We'll let you know as soon as we fix this.

**Comment by Wissi** [comment]
I had misunderstood the use of Multitorches. 
I had thought they were just a way to store 9 torches per block and thus incrementing the stack size of torches considerably.
But I see now that the "multitorch" is to actually shoot (and light up) a larger area (depending on target distance, with 8 torches at once) , very nice idea.

Will try the latest file and if anything comes up we'll let you know so we can keep using your mod in our modpacks.

Thank you very much for your Fix and great work.

**Comment by noriokun4649** [comment]
Thank you.
It certainly was misleading.
To make it easier to understand, I will add how to use the multi torch.
